defaults:
  - env/realworld_so101_ik_reach_check@env.eval
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    env:
      node_group: so101
      placement: 0
  node_groups:
    - label: so101
      node_ranks: 0
      hardware:
        type: SO101
        configs:
          - port: /dev/ttyACM0
            camera_serials: ["233622077247"]
            node_rank: 0

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: "so101-ik-reach-check"
    logger_backends: ["tensorboard"] # wandb, swanlab
  num_data_episodes: 5
  record_task_description: False

env:
  group_name: "EnvGroup"
  eval:
    ignore_terminations: False
    auto_reset: False
    use_spacemouse: False
    override_cfg:
      calibration_path: null
      target_ee_pose: [0.3, 0.0, 0.2, 0.0, 0.0, 0.0]
      success_position_error_m: 0.02
      success_orientation_error_deg: 30.0
      reset_position: [0.2, 0.0, 0.1, 0.0, 0.0]
      check_orientation: false
